version: '3.8'

services:

    backend:
        build: example-backend
        ports:
          - 8080:8080
        environment:
            - REDIS_HOST=redis
    redis:
        image: redis
    frontend:
        build: example-frontend
        ports:
          - 5000:5000
